#!/bin/bash
setup_git() {
  git config --global user.email "travis@travis-ci.org"
  git config --global user.name "Travis CI"
}

commit_coverage_report() {
  git checkout -b code-cov
  git add . 
  git commit --message "Commit code coverage report" --quiet
}

upload_files() {
  git remote add origin-pages https://${GH_TOKEN}@github.com/wongjiahau/ttap-web-test.git > /dev/null 2>&1
  git push --set-upstream origin-pages code-cov -f
}

rm ./.travis.yml #remove this file so that travis won't run build on the code-cov branch
mv codecov.travis.yml .travis.yml #let travis upload code coverage report

sed -i '/coverage/d' ./.gitignore #cancel ignore coverage directory
setup_git
commit_coverage_report
upload_files