#!/bin/bash
setup_git() {
  git config --global user.email "travis@travis-ci.org"
  git config --global user.name "Travis CI"
}

commit_transpiled_resource() {
  git add . 
  git commit --message "Commit transpiled resources" --quiet
}

upload_files() {
  git remote add origin-pages https://${GH_TOKEN}@github.com/wongjiahau/ttap-web-test.git > /dev/null 2>&1
  git push --set-upstream origin-pages master -f
}

# update travis.yml 
echo "$(cat ./test.travis.yml)" > ./travis.yml

sed -i '/core/d' ./.gitignore #cancel ignore core directory which store the transpiled TS
setup_git
commit_transpiled_resource
upload_files